#!/bin/bash

# The pre_start_cartridge and pre_stop_cartridge hooks are *SOURCED*
# immediately before (re)starting or stopping the specified cartridge.
# They are able to make any desired environment variable changes as
# well as other adjustments to the application environment.

# The post_start_cartridge and post_stop_cartridge hooks are executed
# immediately after (re)starting or stopping the specified cartridge.

# Exercise caution when adding commands to these hooks.  They can
# prevent your application from stopping cleanly or starting at all.
# Application start and stop is subject to different timeouts
# throughout the system.
export DEVISE_KEY='f02d3d2fa568a2f7dc70226fcb5e3681f64aff082bf6d325a70a4374f94b21a0290e2d7bb0f4b2ba866f4c24b2a8657746d97a8ce066f4bca89a2e5632a1a541'
export DEVISE_PEPER="2653f26ad968171cb3ffab6cac4165f2655eaba968ed0c424e215e1ec16563fd6419dd1103f71c1d77f6b7375754a001ce309501c92f069dc32535d1a8d0283b"